# Generated by Django 5.0.7 on 2024-07-18 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_member_passwd_member_passwd2_alter_member_qmo_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loc_name", models.CharField(max_length=200)),
                ("loc_description", models.CharField(max_length=150)),
                ("loc_risk", models.CharField(max_length=15)),
                ("loc_comment", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "door_name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name=[
                            ("kitchen", "Kitchen"),
                            ("store_01", "Store_01"),
                            ("store_02", "Store_02"),
                            ("store_03", "Store_03"),
                            ("playground_01", "Playground_01"),
                            ("playground_02", "Playground_02"),
                            ("parents_rm_01", "Parents_rm_01"),
                            ("parents_rm_02", "Parents_rm_02"),
                            ("office_01", "Office_01"),
                            ("office_02", "Office_02"),
                            ("office_03", "Office+03"),
                            ("doctors_office_01", "Doctor's_office_01"),
                            ("doctors_office_02", "Doctors_office_02"),
                        ],
                    ),
                ),
                (
                    "member_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webapp.member",
                    ),
                ),
            ],
        ),
    ]
