# Generated by Django 5.0.7 on 2024-07-18 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_location_risk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loc_name", models.CharField(max_length=200)),
                ("store_01", models.CharField(max_length=150)),
                ("store_02", models.CharField(max_length=15)),
                ("store_03", models.TextField(max_length=500)),
                ("playground_01", models.CharField(max_length=200)),
                ("playground_02", models.CharField(max_length=150)),
                ("parents_rm_01", models.CharField(max_length=15)),
                ("parents_rm_02", models.TextField(max_length=500)),
                ("office_01", models.CharField(max_length=200)),
                ("office_02", models.CharField(max_length=150)),
                ("office_03", models.CharField(max_length=15)),
                ("doctors_office_01", models.TextField(max_length=500)),
                ("doctors_office_02", models.CharField(max_length=200)),
                (
                    "audit_loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.location",
                    ),
                ),
            ],
        ),
    ]
