# Generated by Django 5.0.7 on 2024-07-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_audit_delete_audits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="doctors_office_01",
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="doctors_office_02",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="kitchen",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="loc_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="office_01",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="office_02",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="office_03",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="parents_rm_01",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="parents_rm_02",
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="playground_01",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="playground_02",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="store_01",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="store_02",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="store_03",
            field=models.TextField(max_length=10, null=True),
        ),
    ]
