# Generated by Django 5.0.7 on 2024-07-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0006_alter_audit_doctors_office_01_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="loc_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
