# Generated by Django 5.0.7 on 2024-07-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_alter_audit_loc_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="doctors_office_01",
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="doctors_office_02",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="kitchen",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="loc_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="audit",
            name="office_01",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="office_02",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="office_03",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="parents_rm_01",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="parents_rm_02",
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="playground_01",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="playground_02",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="store_01",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="store_02",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="audit",
            name="store_03",
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
